### ISSUE TITLE
Laying the Milestones 03/01/2021

### ISSUE THREAD

**Issue by mavishak** [NaomiCreate/cnss-app#16]
## Our GitHub Repositories:
[cnss-embedded](https://github.com/mavishak/cnss-embedded) 

_As of now_
- Contains **code** and **Issues** that deal with our **embedded system**.

[cnss-app](https://github.com/NaomiCreate/cnss-app)

_As of now_
- Contains **code** and **Issues** that deal with the **application built to control the embedded system**.
- Contains **Project Milestones**: The project's large picture.
- Contains **Diagrams** and **Planning notes and drafts** we have come up with overtime and contain both embedded and application sides combined.

## Hardware Wise:

- _**STM32-F103RB Microcontroller** - By trial and error, we are slowly learning how to use it._ 
- _**ESP8266 ESP-01 Wi-Fi Module** - We haven't yet started working with it. But we have found a **Technical Reference** that might help [esp8266-technical_reference_en.pdf](https://github.com/NaomiCreate/cnss-app/files/5761545/esp8266-technical_reference_en.pdf)_
- _**HC-SR501 PIR Sensor** - We  managed to activate it as noted in [cnss-embedded/issues #9](https://github.com/mavishak/cnss-embedded/issues/9#issue-772321027)_
- _**OV7670 Camera Module** - We haven't touched it yet._
- _**Jumpers** - We bought all the we need_

## Program Wise:
```diff
- CNSS-APP
```
_**The application**_ is progressing nicely. We are slightly off schedule but have managed to establish the foundations for two app-pages:

- The _**sign-up/log-in**_ page **- This page allows newcomers, security system owners, and system contacts to enter their operative/informative area.
- The _**communications**_ page - This page allows security system owners to assign contacts to their system alerts. 

### TBD:
- [ ] Add to the **_sign-up page_** the ability to enter relevant information aside for email and password.
- [ ] Add to the _**sign-up page**_ a pass-word verification text box.
- [ ]  Arrange CSS in **_communications_** page.
- [ ]  Compare to the original plan - check if changes need to be made.

### Questions raised:
- Should we add a limit to the number of communications (~20)?
- How do we prevent a malicious person from assigning the security system as his own under a different user name?  _(during sign-up we should probably check that the system doesn't exist in current registrations)_
- What will be the assigned ID for the security system device?

```diff
- CNSS-EMBEDDED
```
**_Embedding the security system device_** is progressing slower than we would like. After discussing with our instructor we came to the conclusion that we should keep on and aim high but with alterations to the original plan:

## Revised Plan:

- Try and get STM32 connected with firebase using ESP8266 Wi-Fi Module
