### ISSUE TITLE
Laying the Milestones 08/06/2021

### ISSUE THREAD

**Issue by NaomiCreate** [NaomiCreate/cnss-app#37]
- We have added a password change page that can be accessed from the settings page.

- We added Forms on the login, change password and register page so that he would be warned about basic errors before he tries to log in / register / change password

- We added toast alerts on the history page:
  So if the user finds the history page (whether in "Connections History" or "My History") while a suspicious movement has been 
  detected in his system, toast will appear at the top right of the screen.
  If the user is on the history page under the "Connections History" tag, while suspicious traffic has been detected in his connection system, a toast will appear on the top right of the screen.

  **We used the following links:**
[npmjs: ngx-toastr](https://www.npmjs.com/package/ngx-toastr)
[How to create angular toastr notifications](https://blog.jscrambler.com/how-to-create-angular-toastr-notifications)

- We enabled search alerts on the history page (even when the user is under the tag: My History and also under: Connections History)

### _To Do:_

- [ ] Release version 2 of the system, and let users test it.
- [ ] On the contact list page we need to add a line that says whether the user has set to share his alerts with the contact or not.
- [ ] On the login page add an indication if the email is incorrect.
- [ ] On the search page: Add default value in case no search value is given.
- [ ] When searching on the history page: add a date and time setting with bootstrap (make sure the functionality continues to work with the search).
- [ ] Search History Page: When "show all" is clicked, the other search fields will be emptied, and the search filter will be disabled.

**Note:** 
We decided to try adding motion detection alerts to the user's email and contacts (through the app and firebase)
